services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: face_detector
    ports:
      - 3306:3306
    restart: always
  backend:
    depends_on:
      - mysql
    container_name: fd-backend
    env_file:
      - ./backend/.env
    build: ./backend
    command: npm run start
    ports:
      - 8001:8000
    volumes:
      - ./:/usr/src/backend
    restart: always
  frontend:
    depends_on:
      - backend
    container_name: fd-frontend
    build: ./frontend
    command: npm run start
    ports:
      - 3000:3000
    restart: always
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
